version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - theranotes-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DEBUG=True
      - WHISPER_MODEL_SIZE=base
      - MAX_FILE_SIZE_MB=25
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - theranotes-network

networks:
  theranotes-network:
    driver: bridge

volumes:
  frontend_node_modules:
  backend_pycache:
